dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install --upgrade pip coveralls tox-travis
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3 - --preview --yes
  - source $HOME/.poetry/env
  - poetry install --verbose
script:
  - tox
after_success:
  - coveralls
notifications:
  email: false
